#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

server: server.c Makefile
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o server server.c -lcs -lm

clean:
	rm -f *.o resize whodunit
